import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { KnowledgeStore } from "../graph/store.js";
import type { LLMAdapter } from "../types.js";

/**
 * Save a valuable query answer back into the wiki as a source file,
 * so it can be re-ingested and compound knowledge.
 */
export async function saveAnswerAsSource(
  store: KnowledgeStore,
  question: string,
  answer: string,
  claimIds: string[],
  confidence: number,
  rawDir: string,
): Promise<string> {
  const timestamp = new Date().toISOString();
  const slug = question
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);

  const filename = `synthesis-${slug}.md`;
  const filePath = join(rawDir, filename);

  // Build cited claims section
  const citedClaims = claimIds
    .map((id) => {
      const claim = store.getClaim(id);
      if (!claim) return null;
      return `- [${(claim.confidence * 100).toFixed(0)}%] ${claim.statement}`;
    })
    .filter(Boolean);

  const content = [
    "---",
    `title: "Synthesis: ${question.replace(/"/g, '\\"')}"`,
    `type: note`,
    `quality: blog`,
    `generated_at: "${timestamp}"`,
    `source_question: "${question.replace(/"/g, '\\"')}"`,
    `overall_confidence: ${confidence}`,
    `cited_claims: ${claimIds.length}`,
    "---",
    "",
    `# Synthesis: ${question}`,
    "",
    answer,
    "",
    "## Cited Claims",
    "",
    ...(citedClaims.length > 0 ? citedClaims : ["_No specific claims cited._"]),
    "",
    `---`,
    `*Generated by Quicky Wiki Ask feature on ${timestamp}*`,
    "",
  ].join("\n");

  await mkdir(rawDir, { recursive: true });
  await writeFile(filePath, content, "utf-8");

  return filePath;
}
